e_com/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('reklama.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reklama/urls.py
from django.urls import path
from .import views
app_name = 'reklama'
urlpatterns = [
    path('',views.index,name = 'index'),
    path('elektronika/',views.elekrtonika,name = 'elekrtonika'),
    path('basgalar/',views.basgalar,name = 'basgalar'),
    path('details/<slug:slug>',views.details,name = 'details'),
]

reklama/models.py
from django.db import models
from django.utils.text import slugify


# Create your models here.
class Category(models.Model):
    name = models.CharField( max_length=150)
    class Meta:
        db_table = 'Catagory'
        managed = True
        verbose_name = 'Catagory'
        verbose_name_plural = 'Catagories'
    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField( max_length=150)
    slug = models.SlugField(null=False, blank=True,unique=True,db_index=True,editable=False)
    discription = models.TextField()
    price = models.DecimalField( max_digits=10, decimal_places=2)
    surat = models.FileField(upload_to='product_image',default=None,blank=False)
    Category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    
    def save(self,*args, **kwargs):
        self.slug=slugify(self.name)
        super().save()  
    def __str__(self):
        return self.name
    
    

reklama/views.py
from django.shortcuts import render
from .models import Product, Category
from django.db.models import Q
from django.http import HttpResponse
# Create your views here.


def index(request):
    
    gozleg = request.GET.get('search')
    if gozleg:
        products = Product.objects.filter(Q(name__icontains=gozleg) | Q(discription__icontains=gozleg))
        return render(request,'reklama.html',{'products':products})
    products = Product.objects.all()
    return render(request,'reklama.html',{'products':products})

def elekrtonika(request):
    catagory_ady='Elektronics'

    gozleg = request.GET.get('search')
    if gozleg:
        products = Product.objects.filter(Q(name__icontains=gozleg) | Q(discription__icontains=gozleg))
        return render(request,'reklama.html',{'products':products})


    category = Category.objects.get(name=catagory_ady)
    products = Product.objects.filter(Category=category)
    return render(request,'elektronika.html',{'products':products})



def basgalar(request):
    catagory_ady='Basgalar'

    gozleg = request.GET.get('search')
    if gozleg:
        products = Product.objects.filter(Q(name__icontains=gozleg) | Q(discription__icontains=gozleg))
        return render(request,'reklama.html',{'products':products})


    category = Category.objects.get(name=catagory_ady)
    products = Product.objects.filter(Category=category)
    return render(request,'elektronika.html',{'products':products})


def details(request,slug):

    product = Product.objects.get(slug=slug)
    return render (request, 'details.html',{'product':product})

templates/basgalar.html
{% extends "reklama.html" %}
{% load static %}

{% block content %}
<section id="products" class="products">
    <h2 class="section-title">Elektronika</h2>
    <div class="products-container">
    

        {% for product in products %}
        <div class="product-box">
            <img src="{{product.surat.url}}" alt="Product 1" class="product-img">
            <h3>{{product.name}}</h3>

            <h1>{{product.price}} TMT</h1>
        </div>

        {% endfor %}

{% endblock content %}

templates/details.html

{% load static %}

{% block content %}
<section id="products" class="products">
    <h2 class="section-title">Elektronika</h2>
    <div class="products-container">
    
   
        <div class="product-box">
            <img src="{{product.surat.url}}" alt="Product 1" class="product-img" width=100px>
            <h3>{{product.name}}</h3>
            <h2>{{product.discription}}</h2>

            <h1>{{product.price}} TMT</h1>
        </div>



{% endblock content %}

templates/elektronika.html
{% extends "reklama.html" %}
{% load static %}

{% block content %}
<section id="products" class="products">
    <h2 class="section-title">Elektronika</h2>
    <div class="products-container">
    

        {% for product in products %}
        <div class="product-box">
            <img src="{{product.surat.url}}" alt="Product 1" class="product-img">
            <h3>{{product.name}}</h3>

            <h1>{{product.price}} TMT</h1>
        </div>

        {% endfor %}

{% endblock content %}

templates/reklama.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gyrat</title>
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <script src="{% static "js/js.js" %}" defer ></script>
</head>
<body>
    <header class="header">
    <div class="logo-cotainer">
        <img src="{% static 'images/gyrat logo png.png'%}" alt="Logotip" class="logo">
    </div>
    <div class="search-container">
        <form method="GET" action="">
            <input type="text" name="search" placeholder="Gozleg..." class="search-input">
            <button class="search-btn"><img src="{% static 'images/loupe_78956.png'%}" alt="Gozleg lupa" class="search-icon"> </button>
        </form>
        
    </div>
    <div class="burger-menu" onclick="toggleMenu()">
        <span></span>
        <span></span>
        <span></span>
    </div>
    
    <nav id="nav-menu">
        <a href='{% url 'reklama:elekrtonika' %}'>Elektronika</a>

        <a href='{% url 'reklama:index' %}'>Umumy bildirişler</a>

        <a href="{% url 'reklama:basgalar' %}">Başgalar</a>
    </nav>
    </header>
{% block content %}
    <section id="products" class="products">
        <h2 class="section-title">Umumy bildirişler</h2>
        <div class="products-container">
        

            {% for product in products %}
            <div class="product-box">
                <a href="{% url 'reklama:details' slug=product.slug %}">
                <img src="{{product.surat.url}}" alt="Product 1" class="product-img">
                </a>
                <h3>{{product.name}}</h3>

                <h1>{{product.price}} TMT</h1>
            </div>

            {% endfor %}

{% endblock content %}         
        </div>
        
    </section>

    <footer class="footer">
        <div class="footer-content">
            <div class="footer-logo">
                <img src="{% static 'images/gyrat logo png.png'%}" alt="Logotip" class="logo">
                   
            </div>
          
              
                <div class="contact-info">
                    <img src="{% static 'images/imo_14110.png'%}" alt="IMO" class="contact-icon-img">
                    <span class="phone-number">+(993) 61527304 </span>
                </div>
        
        </div>
        
        <p>&copy; 2024 Gyrat. </p>
      
    </footer>

</body>
</html>